server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/elastic_search_demo?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  # elasticSearch
  elasticsearch:
    rest:
      uris: http://192.168.116.128:9200
  # rabbitmq
  rabbitmq:
    host: 192.168.116.128
    port: 5672
    username: itcast
    password: 123456
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo
